### ISSUE TITLE
request

### ISSUE THREAD

**Issue by TechnoIndian** [hngocuyen/pymeomeoobfuscator#1]

**Comment by hngocuyen** [comment]
lol obf only credit can replace bro and this obf have a 'protect function' so if i public a source this can bypass lol , if u want obf open source u can open enjuly19 and velimatix in my repo , this dont have protect function for anti cracking , only protect code

**Comment by TechnoIndian** [comment]
> lol obf only credit can replace bro and this obf have a 'protect function' so if i public a source this can bypass lol , if u want obf open source u can open enjuly19 and velimatix in my repo , this dont have protect function for anti cracking , only protect code

Good, but then you should have only encrypt the anti-cracking code and not the full script. Anyway, if anti-cracking is kept as a user choice, then why do you need to encrypt the full script?

As far as enjuly19 encryption is concerned, it reduces the execution speed of the script
